#!/usr/bin/env sh

install() {
	if [ $# -gt 1 ]; then
		mkdir -p "/etc/portage/package.use/${1%*/}"
		IFS=' ' printf '%s\n ' "$*" >>"/etc/portage/package.use/$1"
		shift $(($# - 1))
	fi
	log="$(mktemp)"
	eval "$INSTALL $1" > "$log" 2>&1  || installfail "$1" "$log" || exit 1
	rm "$log"
}

installfail() {
	autounmask_file='/etc/portage/package.accept_keywords/zzz_autounmask'
	[ -f "$autounmask_file" ] || touch "$autounmask_file"

	set -e
	case "$(cat "$2")" in
		*"MASKED PACKAGES"*)
			emerge --autounmask --autounmask-continue "$1"
			mkdir -p "/etc/portage/package.accept_keywords/${1%*/}"
			mv "$autounmask_file" "/etc/portage/package.accept_keywords/$1"
			;;
	esac

	"$INSTALL" "$1"
	set +e
}
