#!/usr/bin/env sh

DOTS_REPO='git@github.com:subado/dots'
DOTS_GIT_DIR='.cfg/.git'

after_clone() {
	dots="$1"
	if [ -r "$dots/.profile" ]; then
		read -r shell <"$dots/.profile"
		env_dump=$(eval "
		${shell#'#!'} -c \"
			. $dots/.profile;
			env\"
		")
	fi

	while read -r sl; do
		file="$HOME/${sl#"$dots/"}"
		[ -h "$file" ] || mv -f "$file" "${file%/*}/$(readlink "$sl")"
	done <<-_EOF
		"$(find "$dots" -type l)"
	_EOF

	set -- 'CARGO_HOME' "$HOME/.cargo" 'GNUPGHOME' "$HOME/.gnupg" 'GOMODCACHE' "$HOME/go/mod" 'GOPATH' "$HOME/go" 'TASKDATA' "$HOME/.task"
	while [ $# -ne 0 ]; do
		env "$env_dump" ./mv_if_set "$1" "$2"
		shift 2
	done
}
